export default {
    faculty: `../uploads/faculty-uploads`,
    CAS: `../uploads/faculty-uploads/CAS-uploads`,
    PBAS: `../uploads/faculty-uploads/PBAS-uploads`,
    director: `../uploads/director-uploads`,
    AAA: `../uploads/director-uploads/AAA-uploads`,
    student: `../uploads/student-uploads`,
    alumni: `../uploads/director-uploads`,
    news: `../uploads/news-uploads`,
    event: `../uploads/event-uploads`,
    school: `../uploads/school-uploads`,
    FeedbackATR: `../uploads/feedback-uploads`,
    admin: `../uploads/admin-uploads`,
    program: `../uploads/program-uploads`,
    dsd: `../uploads/dsd-uploads`,
    krc: `../uploads/krc-uploads`,
    sports: `../uploads/sports-uploads`,
    nss: `../uploads/nss-uploads`,
    exam: `../uploads/exam-uploads`,
    placement: `../uploads/placement-uploads`,
    iil: `../uploads/iil-uploads`,
    aqar: `../uploads/aqar-uploads`,
    youth: `../uploads/youth-uploads`,
    skill: `../uploads/skilldevelopment-uploads`,
    swayam: `../uploads/swayam-uploads`,
    estt: `../uploads/establishment-uploads`,
    tpo: `../uploads/tpo-uploads`,
}