const newObj = {
  "Ph.D. (Computer Science)": "Ph.D. Computer Science",
  "M.Phil (Computer Science)": "M.Phil. Computer Science",
  "MCA": "MCA",
  "M.Sc.(Computer Science)": "M.Sc. Computer Science",
  "M.Sc(Computer Applications)": "M.Sc. Computer Applications",
  "M.Sc(Computer Networking)": "M.Sc. Computer Networking",
  "M.Sc.(Chemistry)": "M.Sc. Chemistry",
  "M.Sc.(Chemistry Analytical)": "M.Sc. Chemistry Analytical",
  "M.Sc.(Chemistry Industrial)": "M.Sc. Chemistry Industrial",
  "M.Sc.(Chemistry Medicinal": "M.Sc. Chemistry Medicinal",
  "M.Sc.(Chemistry Organic)": "M.Sc. Chemistry Organic",
  "M.Sc.(Chemistry Physical": "M.Sc. Chemistry Physical",
  "M.Sc.(Polymer chemistry)": "M.Sc. Polymer Chemistry",
  "M. Phil.(Chemistry)": "M.Phil. Chemistry",
  "Ph.D.(Chemistry)": "Ph.D. Chemistry",
  "MBA": "MBA",
  "M.Com": "M.Com.",
  "M.Phil(Commerce)": "M.Phil. Commerce",
  "M.Phil(Management)": "M.Phil. Management",
  "Ph.D(Commerce)": "Ph.D. Commerce",
  "Ph.D(Management)": "Ph.D. Management",
  "M.P.Ed.": "M.P.Ed.",
  "M.Ed.": "M.Ed.",
  "M.Phil.(Phy.Edu.)": "M.Phil. Physical Education",
  "M.Phil.(Education)": "M.Phil. Education",
  "Ph.D.(Phy.Edu.)": "Ph.D. Physical Education",
  "Ph.D.(Education)": "Ph.D. Education",
  "M.Sc.(Geology)": "M.Sc. Geology",
  "M.Sc.(Environmental Science)": "M.Sc. Environmental Science",
  "M.A/M.Sc.(Geography)": "M.A/M.Sc. Geography",
  "M.Sc.(Geophysics)": "M.Sc. Geophysics",
  "M.Phil.(Geology)": "M.Phil. Geology",
  "M.Phil.(Environmental Science)": "M.Phil. Environmental Science",
  "M.Phil.(Geography)": "M.Phil. Geography",
  "Ph.D.(Geology)": "Ph.D. Geology",
  "Ph.D.(Environmental Science)": "Ph.D. Environmental Science",
  "Ph.D.(Geography)": "Ph.D. Geography",
  "Ph.D.(Geophysics)": "Ph.D. Geophysics",
  "Post-Graduate Diploma in Geoinformatics": "PG Diploma in Geoinformatics",
  "Certificate Course in Industrial Safety,Health and Environmental Management (dual course with PG, M.Phil & Ph.D.)": "Certificate Course in Industrial Safety, Health and Environmental Management (dual course with PG, M.Phil. & Ph.D.)",
  "Bachalor in Performing Arts": "Bachelor in Performing Arts",
  "M.A.(Theater Arts & Film)": "M.A. Theater Arts & Film",
  "M.A.(Music)": "M.A. Music",
  "Diploma in Theater Arts": "Diploma in Theater Arts",
  "Certificate Course in Music": "Certificate Course in Music",
  "Certificate Course in Dance": "Certificate Course in Dance",
  "M.A.(English)": "M.A. English",
  "M.A.(Marathi)": "M.A. Marathi",
  "M.Phil.(English)": "M.Phil. English",
  "M.Phil.(Marathi)": "M.Phil. Marathi",
  "Ph.D.(English)": "Ph.D. English",
  "Ph.D.(Marathi)": "Ph.D. Marathi",
  "Ph.D.(Hindi)": "Ph.D. Hindi",
  "Ph.D.(Urdu)": "Ph.D. Urdu",
  "Certificate Course  in French Language": "Certificate Course in French Language",
  "Diploma Course in French Language": "Diploma Course in French Language",
  "Advance Diploma in French Language": "Advance Diploma in French Language",
  "Certificate Course  in Spanish Language": "Certificate Course in Spanish Language",
  "Diploma Course in Spanish Language": "Diploma Course in Spanish Language",
  "Advance Diploma in Spanish Language": "Advance Diploma in Spanish Language",
  "Post Graduate Diploma in Medical Laboratory Technology (PGDMLT)": "PGDMLT",
  "M.Sc.(Biotechnology)": "M.Sc. Biotechnology",
  "M.Sc.(Zoology)": "M.Sc. Zoology",
  "M.Sc.(Botany)": "M.Sc. Botany",
  "M.Sc.(Microbiology)": "M.Sc. Microbiology",
  "M.Phil.(Biotechnology)": "M.Phil. Biotechnology",
  "M.Phil.(Zoology)": "M.Phil. Zoology",
  "M.Phil.(Botany)": "M.Phil. Botany",
  "M.Phil.(Microbiology)": "M.Phil. Microbiology",
  "Ph.D.(Biotechnology)": "Ph.D. Biotechnology",
  "Ph.D.(Zoology)": "Ph.D. Zoology",
  "Ph.D.(Botany)": "Ph.D. Botany",
  "Ph.D.(Microbiology)": "Ph.D. Microbiology",
  "Ph.D.(Bioinformatics)": "Ph.D. Bioinformatics",
  "M.Sc.(Mathematics)": "M.Sc. Mathematics",
  "M.Sc.(Statistics)": "M.Sc. Statistics",
  "M.Phil.(Mathematics)": "M.Phil. Mathematics",
  "Ph.D.(Mathematics)": "Ph.D. Mathematics",
  "Ph.D.(Statistics)": "Ph.D. Statistics",
  "M.A./M.Sc(Electronic Media)": "M.A./M.Sc. Electronic Media",
  "M.A.(Mass Communication & Journalism)": "M.A. Mass Communication & Journalism",
  "M.Phil.(Mass Communication & Journalism)": "M.Phil. Mass Communication & Journalism",
  "Ph.D.(Mass Communication & Journalism)": "Ph.D. Mass Communication & Journalism",
  "B.Pharm": "B.Pharm.",
  "M.Pharm(Pharmaceutics)": "M.Pharm. Pharmaceutics",
  "M.Pharm(Pharmaceutical Chemistry)": "M.Pharm. Pharmaceutical Chemistry",
  "M.Pharm(Pharmacology)": "M.Pharm. Pharmacology",
  "M.Pharm(Quality Assurance)": "M.Pharm. Quality Assurance",
  "M.Pharm(Pharmaceutical Sciences)": "M.Pharm. Pharmaceutical Sciences",
  "Ph.D.(Pharmaceutical Sciences)": "Ph.D. Pharmaceutical Sciences",
  "M.Sc.(Physics)": "M.Sc. Physics",
  "M.Phil.(physics)": "M.Phil. Physics",
  "Ph.D.(Physics)": "Ph.D. Physics",
  "MSW": "MSW",
  "M.A.(Applied Economics)": "M.A. Applied Economics",
  "M.A.(Sociology)": "M.A. Sociology",
  "M.A.(Human Rights)": "M.A. Human Rights",
  "M.Phil(Social Work)": "M.Phil. Social Work",
  "M.Phil(Sociology)": "M.Phil. Sociology",
  "M.Phil(Human Rights)": "M.Phil. Human Rights",
  "Ph.D.(Social Work)": "Ph.D. Social Work",
  "Ph.D.(Sociology)": "Ph.D. Sociology",
  "Ph.D.(Applied Economics)": "Ph.D. Applied Economics",
  "Ph.D.(Human Rights)": "Ph.D. Human Rights",
  "P.G.Diploma in Women's Studies": "PG Diploma in Women's Studies",
  "Interdisciplinary Certificate Course in Women's Studies": "Interdisciplinary Certificate Course in Women's Studies",
  "M.B.A": "MBA",
  "M.Com": "M.Com.",
  "PGDDM": "PGDDM",
  "M.Phil(Management Sciences)": "M.Phil. Management Sciences",
  "Ph.D(Management Sciences)": "Ph.D. Management Sciences",
  "Certificate Course in Goods and Service Tax (GST)": "Certificate Course in GST",
  "M.A.(Economics)": "M.A. Economics",
  "M.A.(Sociology)": "M.A. Sociology",
  "M.S.W.": "MSW",
  "Ph.D.(Social Science)": "Ph.D. Social Science",
  "Data Interpretation Using MS-Excel and SPSS": "Data Interpretation Using MS-Excel and SPSS",
  "B.Voc.(Software Development)": "B.Voc. Software Development",
  "M.Sc.(Computer Science Integrated)": "M.Sc. Computer Science Integrated",
  "M.Sc.(Bioinformatics)": "M.Sc. Bioinformatics",
  "M.Phil.(Computer Science)": "M.Phil. Computer Science",
  "Ph.D.(Computer Science)": "Ph.D. Computer Science",
  "Ph.D.(Bioinformatics)": "Ph.D. Bioinformatics"
};