const excelObject = {
    //director
    Award: {
        'Title_of_the_innovation': 'Title of the innovation',
        'Name_of_the_Award': 'Name of the Award',
        'Name_of_the_Awarding_Agency': 'Name of the Awarding Agency',
        'Contact_details_Agency': 'Contact details Agency',
        'Year_of_Award': 'Year of Award',
        'Category': 'Category',
    },
    ConferencesSemiWorkshopOrganized: {
        'Year': 'Year',
        'Title_Of_the_Program': 'Title Of the Program',
        'Level_of_program': 'Level of Program',
        'Number_of_Participants': 'Number of Participants',
    },
    CounselingAndGuidance: {
        'Name_of_the_Activity_conducted_by_the_HEI': 'Name of the Activity conducted by the HEI',
        'Number_of_Students_Attended': 'Number of Students Attended',
        'Year_of_Activity': 'Year of Activity',
    },
    DemandRatio: {
        'Programme_Code': 'Program Code',
        'Programme_name': 'Program name',
        'Academic_Year': 'Academic Year',
        'Number_of_seats_available': 'Number of seats available',
        'Number_of_eligible_applications': 'Number of eligible applications',
        'Number_of_Students_admitted': 'Number of Students admitted',
        'Type_of_program': 'Type of program',
    },
    Employability: {
        "Program_Name": "Program Name",
        'Course_Code': 'Course Code',
        'Name_of_the_Course': 'Name of the Course',
        'Academic_Year': 'Academic Year',
        'Year_of_introduction': 'Year of introduction',
        'Activities_Content_with_direct_bearing_on_Employability_Entrepreneurship_Skill_development': 'Activities Content with direct bearing on Employability Entrepreneurship Skill development',
    },
    ExtensionActivities: {
        'Name_of_the_activity': 'Name of the activity',
        'Organising_unit': 'Organising unit/ agency/ collaborating agency',
        'Name_of_the_scheme': 'Name of the scheme',
        'Year_of_activity': 'Year of activity',
        'Number_of_students': 'Number of students',
    },
    IctClassrooms: {
        'Room_number_or_Name_of_Classrooms': 'Room number or Name of Classrooms',
        'Type_of_ICT_facility': 'Type of ICT facility'
    },
    MoUs: {
        'Name_of_Organisation_with_whome_mou_signed': 'Name of Organisation with whome mou signed',
        'Duration_of_MoU': 'Duration of MoU',
        'Year_of_signing_MoU': 'Year of signing MoU',
    },
    Placement: {
        "Name_of_student_placed": "Name of student placed",
        "Program_graduated_from": "Program graduated from",
        "Name_of_the_employer": "Name of the employer",
        "Employer_contact_details": "Employer contact details",
        "Pay_package_annum": "Pay package annum",
        "Academic_Year": "Academic Year",
        'Type_Of_Placement': "Type Of Placement",
    },
    ProgressionToHE: {
        'Name_of_student_enrolling': 'Name of student enrolling',
        'Program_graduated_from': 'Program graduated from',
        'Name_of_institution_admitted': 'Name of institution admitted',
        'Name_of_programme_admitted': 'Name of program admitted',
        'Academic_Year': 'Academic Year',
    },
    ProjectsInternships: {
        "Programme_Code": "Program Code",
        "Programme_name": "Program name",
        "Academic_Year": "Academic Year",
        "Name_of_the_student": "Name of the student",
    },
    QualifiedExams: {
        'Acadmic_year': "Acadmic year",
        'Registration_number_roll_number': "Registration number roll number",
        'Names_of_students_selected_qualified': "Name of student qualified",
        'Name_of_the_Exam': "Name of the Exam",
    },
    ReservedSeats: {
        "Academic_Year": "Academic Year",
        "Program_Name": "Program Name",
        "NseSC": "SC1",
        "NseST": "ST1",
        "NseOBC": "OBC(VJNT)1",
        "NseDivyngjan": "Divyngjan1",
        "NseGeneral": "General1",
        "NseOthers": "Others1",
        "NsaSC": "SC2",
        "NsaST": "ST2",
        "NsaOBC": "OBC(VJNT)2",
        "NsaDivyngjan": "Divyngjan2",
        "NsaGeneral": "General2",
        "NsaOthers": "Others2",
    },
    ResearchMethodologyWorkshops: {
        "Name_of_the_workshop_seminar": "Name of the workshop seminar",
        "Number_of_Participants": "Number of Participants",
        "year": "year",
        "From_Date": "From Date",
        "To_Date": "To Date",
    },
    TrainingProgramsOrganized: {
        "Year": "Year",
        "From_Date": "From Date",
        "To_Date": "To Date",
        "Title_Of_the_Program": "Title Of the Program",
        "Type_of_staff": "Type of staff",
        "Number_of_Participants": "Number of Participants",
        "Level_of_program": "Level of program",
    },
    UgcSapCasDstFistDBTICSSR: {
        "Name_of_the_Scheme_Project_Endowments_Chairs": "Name of the Scheme Project Endowments Chairs",
        "Name_of_the_Principal_Investigator_Co_Investigator": "Name of the Principal Investigator Co-Investigator",
        "Name_of_the_Funding_agency": "Name of the Funding agency",
        "Type_of_Agency": "Type of Agency",
        "Name_of_Department": "Name of Department",
        "Year_of_Award": "Year of Award",
        "Funds_provided_in_lakhs": "Funds provided in lakhs",
        "Duration_of_the_project_in_Years": "Duration of the project in Years",
    },
    StudentSatisfactionSurvey: {
        "Name_of_the_student": "Name of the student",
        "Year_of_joining": "Year of joining",
        "Category": "Category",
        "State_of_Domicile": "State of Domicile",
        "Nationality": "Nationality",
        "Email_ID": "Email ID",
        "Programme_name": "Program name",
        "Student_Unique_Enrolment_ID": "Student Unique Enrolment ID",
        "Mobile_Number": "Mobile Number",
        "Gender": "Gender",
    },
    SkillsEnhancementInitiatives: {
        "Name_of_the_capacity_development_schemes": "Name of the capacity development schemes",
        "Academic_Year": "Academic Year",
        "Number_of_students_enrolled": "Number of students enrolled",
    },
    ValueAddedCource: {
        "Program_Name": "Program Name",
        "Name_of_the_value_added_courses_offered": "Name of the value added courses offered",
        "Course_Code_if_any": "Course Code (if any)",
        "Academic_year": "Academic year",
        "Year_of_offering": "Year of offering",
        "No_of_times_offered_during_the_same_year": "No of times offered during the same year",
        "Duration_of_the_course": "Duration of the course (in Months)",
        "Number_of_students_enrolled": "Number of students enrolled",
        "Number_of_Students_completing_the_course": "Number of Students completing the course",
    },
    SyllabusRevision: {
        "Programme_Code": "Program Code",
        "Programme_Name": "Program Name",
        "Academic_Year": "Academic Year",
        "Year_of_Introduction": "Year of Introduction",
        "Status_of_implementation": "Status of implementation",
        "Year_of_Implimentation": "Year of Implimentation",
        "Year_of_Revision": "Year of Revision",
        "Percentage_of_content_added_or_replaced": "Percentage of content added or replaced",
    },
    AlumniContribution: {
        "Name_of_The_Alumni_Contributed": "Name Of The Alumni",
        "Program_graduated_from": "Program Graduated From",
        "Amount_of_contribution": "Contribution Ammount in ₹",
        "Academic_Year": "Year of Contribution",
    },
    CourceInAllProgram: {
        'programName': "Program Name",
        'programCode': "Program Code",
        'courseName': "Course Name", 
        'courseCode': "Course Code",
        'academicYear': "Academic Year",
    },
    NewPrograms: {
        'programName': "Program Name",
        'programCode': "Program Code",
        'academicYear': "Academic Year",
    },

    //Faculty 
    AppointmentsHeldPrior: {
        'designation': 'Designation',
        'employerName': 'Employer Name',
        'joiningDate': 'From',
        'leavingDate': 'To',
        'salaryWithGrade': 'Salary with grade',
        'leavingReason': 'Leaving Reason',
    },
    Degree: {
        'degreeName': 'Degree',
        'title': 'Title',
        'university': 'University',
        'awardDate': 'Award Date',
        'subject': 'Subject',
    },
    Qualification: {
        'exam': 'Exam',
        'institute': 'Institute/Board',
        'year': 'Year',
        'percentage': 'Percentage',
        'subjects': 'Subjects',
    },
    ResearchProject: {
        'schemeName': "Scheme or Project Name",
        'principalName': "Principal Invigilator Name",
        'fundingName': "Funding Agency Name",
        'isGov': "Wheather Government / Non-Government",
        'awardYear': "Award Year",
        'projectDuration': "Project Duration (In Year)",
        'providedFunds': "Provided Funds (INR)",
        'fundType': "Wheather Major / Minor",
        'status': "Status",
        'year': "Choose Year",
    },
    PostHeld: {
        'designation': "Designation",
        'department': "Department",
        'joiningDate': "Joining Date",
        'leavingDate': "Leaving Date",
    },
    Lectures: {
        'course': 'Course/Paper',
        'level': 'Level',
        'teachingMode': 'Teaching Mode',
        'noOfClasses': 'No of classes alloted',
        'classesTaken': 'No of classes taken',
        'year': ' Year',
    },
    EContentDeveloped: {
        'moduleName': 'Name of the Module / Course developed',
        'creationType': 'Type of Creation',
        'platform': 'Platform on which the module is developed',
        'year': 'Choose Year',
        'link': 'Link to the content',
    },
    ResearchPaper: {
        'paperTitle': 'Paper Title',
        'journalName': 'Journal Name',
        'authors': "Author(s)",
        'publicationYear': 'Publication Year',
        'issnNumber': 'ISSN Number',
        'year': 'Choose Year',
    },
    BookAndChapter: {
        'type': 'Type',
        'titleOfBook': 'Title of Book / Chapter / Edited Book / Translation',
        'paperTitle': 'Paper Title',
        'titleOfProceeding': 'Title of proceedings of the conference',
        'conName': 'Conference Name',
        'isNat': 'Wheather National / International',
        'authorEditor': 'Author / Editor / Translator',
        'publicationYear': 'Year of Publication',
        'issnNumber': 'ISBN/ISSN number of proceeding',
        'aff': 'Affiliation Institute at the time of publication',
        'year': 'Choose Year',
        'publisherName': 'Publisher Name',
    },
    PhdAwarded: {
        'scholarName': 'Scholar Name',
        'departmentName': 'Department Name',
        'guideName': 'Guide Name',
        'rac': 'Date of Registration (RAC)',
        'category': 'Category',
        'gender': 'Gender',
        'degreeName': 'Degree',
        'awardSubmit': 'Awarded / Submitted',
        'thesisTitle': 'Thesis Title',
        'yearOfScholar': 'Year of Scholar Registration',
        'phdAwardYear': 'Year of Award',
        'year': 'Choose Year',
    },
    JrfSrf: {
        'researchName': 'Research Fellow Name',
        'enrolmentYear': 'Enrolment Date',
        'fellowshipDuration': 'Fellowship Duration',
        'fellowshipType': 'Fellowship Type',
        'grantingAgency': 'Granting Agency',
        'qualifyingExam': 'Qualifying Exam (if any)',
        'year': 'Choose Year',
    },
    AwardRecognition: {
        'teacherName': 'Name of full-time teachers receiving award',
        'awardYear': 'Award Date',
        'pan': 'PAN',
        'designation': 'Designation',
        'awardName': 'Name of the Award, Fellowship, received',
        'isNat': 'Wheather National / International',
        'incentive': 'Incentives/Type of incentive given by the HEI in recognition of the award',
        'agencyName': 'Award Agency Name',
        'year': 'Choose Year',
    },
    Patent: {
        'patenterName': 'Patenter Name',
        'patentNumber': 'Patent Number',
        'patentTitle': 'Patent Title',
        'isNat': 'Wheather National / International',
        'awardYear': 'Award Year of Patent',
        'year': 'Choose Year',
    },
    ConsultancyServices: {
        'cName': 'Consultant Name',
        'cProjectName': 'Consultancy Project Name',
        'cAgency': 'Consulting / Sponsoring Agency with contact',
        'cYear': 'Consultancy Year',
        'revenue': 'Revenue Generated(INR)',
        'year': 'Year',
    },
    Collaboration: {
        'collabTitle': 'Title of the collaborative activity',
        'agencyName': 'Name of the collaborating agency with contact details',
        'participantName': 'Participant Name',
        'collabYear': 'Year of Collaboration',
        'duration': 'Duration',
        'activityNature': 'Nature of the activity',
        'year': 'Year',
    },
    InvitedTalk: {
        'lectureTitle': 'Title of Lecture/Academic Session',
        'seminarTitle': 'Title of Seminar, etc.',
        'organizedBy': 'Organized by',
        'isNat': 'Type',
        'nature': 'Nature',
        'year': 'Year',
    },
    ConferenceOrganized: {
        'programTitle': 'Program Title',
        'schoolName': 'School Name',
        'fundedBy': 'Funded By',
        'isNational': 'Level',
        'noOfParticipants': 'No of Participants',
        'year': 'Year',
    },
    ConferenceParticipated: {
        'programTitle': 'Program Title',
        'organizingInstitute': 'Organizing Institute',
        'isNational': 'National / International',
        'year': 'Year',
    },
    Fellowship: {
        'teacherName': 'Name of the teacher awarded national/international fellowship/financial support',
        'awardName': 'Name of the award/fellowship',
        'awardingAgency': 'Awarding Agency',
        'awardYear': 'Award Year',
        'isNat': 'National / International',
        'year': 'Year',
    },
    Online: {
        'programTitle': 'Program Title',
        'nameOfAttendedTeacher': 'Organized by',
        'durationFrom': 'Duration From',
        'durationTo': 'Duration To',
        'year': 'Year',
    },
    FinancialSupport: {
        'nameOfConference': 'Name of Conference',
        'feeprovider': 'Name of professional body Funds provided for',
        'amountOfSupport': 'Amount of support',
        'pan': 'PAN No.',
        'year': 'Year',
    },
    Responsibilities: {
        'committeeName': 'Name of the Committee',
        'designation': 'Designation',
        'institute': 'Hosting institute name',
        'year': 'Year',
    },
    ForeignVisit: {
        'purposeOfVisit': 'Purpose Of Visit',
        'nameOfTheInstitutionVisited': 'Name Of The Institute Visited',
        'fromDate': 'From',
        'toDate': 'To',
        'year': 'Year',
    },
    //Nss
    NssBasicInfo: {
        'studentName': "Student Name", 
        'parentName': "Father/Mother Name", 
        'dob': "Date of Birth", 
        'gender': "Gender", 
        'state': "State", 
        'distric': "Distric", 
        'mobileNo': "Mobile No", 
        'address': "Address", 
        'email': "Email", 
        'createdByEmail': "Created by Programme. Officer Email", 
        'otherAreaOfInterest': "Other Area Of Interest",
    },
    NssAdmission:{
        'studentName': "Student Name", 
        'classes': "Class", 
        'dob': "Date of Birth", 
        'caste': "Caste", 
        'category': "Category", 
        'nss1Year': "Year of NSS-1", 
        'nss2Year': "Year of NSS-2", 
        'address': "Address", 
        'email': "Email", 
        'projectName': "Project Assigned", 
        'bloodGroup': "Blood Group",
    },
     //EXAM
     ExamPassedDuringYear: {
       'programCode': "Program Code", 'programName': "Program Name", 'studentsAppeared': "Number of Students Appeared in Final Year Examination", 'studentsPassed': "Number of Students Passed in Final Year Examination", 'academicYear': 'Year',
   },
   StudentComplaintsGrievances:{
       'noOfStudents': "No Of Students Appeared", 'noOfGrievances': "No Of Grievances", 'academicYear': 'Year',
   },
   DateOfResultDiclaration:{
       'programmeName': "Programme Name", 'programmeCode': "Programme Code", 'academicYear': "Semester/ year", 'lastDate': "Last date of the last semester-end/ year- end examination", 'diclarationDate': "Date of declaration of results of semester-end/ year- end examination",
   }
}

export default excelObject;