let siteLinks = {
    welcome: { title: 'Welcome', link: '/' },
    adminHome: { title: 'Admin Dashboard', link: '/admin' },
    facultyHome: { title: 'Faculty Home', link: '/faculty' },
    facultyProfile: { title: 'Faculty Profile', link: '/faculty/faculty-profile' },
    facultyReport: { title: 'Faculty Report', link: '/faculty/service/generateFacultyReport' },
    facultyLogin: { title: 'Faculty Login', link: '/faculty-login' },
    facultyPasswordReset: { title: "Faculty Password Reset", link: '/services/forgot-password/faculty' },
    facultyRegistration: { title: 'Faculty Registration', link: '/faculty-registration' },
    contractualFacultyRegistration: { title: 'Contractual Faculty Registration', link: '/contractual-faculty-registration' },
    facultyChangePass: { title: 'Change Password', link: '/changePassword' },
    cas: { title: 'CAS Report', link: '/faculty/service/cas-report' },
    casReport: { title: 'Generate CAS Report', link: '/faculty/service/generateCASReport' },
    pbas: { title: 'PBAS Report', link: '/faculty/service/pbas-report' },
    pbasReport: { title: 'Generate PBAS Report', link: '/faculty/service/generatePBASReport' },
    aqar: { title: 'Faculty AQAR Report', link: '/faculty/service/aqar-report' },
    aqarReport: { title: 'Generate AQAR Report', link: '/faculty/service/generateAQARReport' },
    directorAqar: { title: 'Director AQAR Report', link: '/director/service/aqar-report' },
    directorAqarReport: { title: 'Generate AQAR Report', link: '/director/service/generateAQARReport' },
    aaaReport: { title: 'Academic & Administrative Audit Report', link: '/director/service/generateAAAReport' },
    directorReport: { title: 'Director Report', link: '/director/service/generateDirectorReport' },
    directorPasswordReset: { title: "Director Password Reset", link: '/services/forgot-password/director' },
    directorHome: { title: 'Director Home', link: '/director' },
    directorLogin: { title: 'Director Login', link: '/director-login' },
    directorRegistration: { title: 'Director Registration', link: '/director-registration' },
    sdm: { title: 'SDM', link: '/director/sdm' },
    ssm: { title: 'SSM', link: '/director/ssm' },
    aaa: { title: 'Academic Audit  ', link: '/director/service/academic-audit' },
    alumniLogin: { title: 'Alumni Login', link: '/alumni-login' },
    alumniHome: { title: 'Alumni Home', link: '/alumni' },
    alumniPasswordReset: { title: "Alumni Password Reset", link: '/services/forgot-password/alumni' },
    alumniRegistration: { title: 'Alumni Registration', link: '/alumni-registration' },
    alumniStatus: { title: 'Alumni Status', link: '/alumni/alumni-status' },
    studentLogin: { title: "Student Login", link: '/student-login' },
    studentHome: { title: "Student Home", link: '/student' },
    studentRegistration: { title: "Student Registration", link: '/student-registration' },
    studentPasswordReset: { title: "Student Password Reset", link: '/services/forgot-password/student' },
    studentStatus: { title: "Student Status", link: '/student/student-status' },
    allNews: { title: "All News", link: '/news' },
    proLogin: { title: "PRO Login", link: '/pro-login' },
    proEditor: { title: "PRO Editor", link: '/pro-editor' },
    proHome: { title: "PRO Home", link: '/pro' },
    adminDashboard: { title: "Admin Dashboard", link: '/admin' },
    forgotPassword: { title: "Forgot Password", link: '' },
    generateFeedbackLinksDirector: { title: "Generate Feedback Links", link: '/director/service/generateFeebackLinks' },
    goToResponse: { title: "Select Response", link: '/director/service/goToResponse' },
    serviceStatusForDirector: { title: "Report Status for Director", link: '/director/service/status' },
    serviceStatusForAdmin: { title: "Report Status for Admin", link: '/admin/service/status' },
    studentFeedack: { title: "Student Feedback Form", link: '/feedback/student' },
    teacherFeedack: { title: "Teacher Feedback Form", link: '/feedback/teacher' },
    parentFeedack: { title: "Parent Feedback Form", link: '/feedback/parent' },
    alumniFeedack: { title: "Alumni Feedback Form", link: '/feedback/alumni' },
    employerFeedack: { title: "Employer Feedback Form", link: '/feedback/employer' },


}
export default siteLinks;
