let siteLinks = {
    welcome: { title: 'Welcome', link: '/' },
    facultyHome: { title: 'Faculty Home', link: '/faculty' },
    facultyProfile: { title: 'Faculty Profile', link: '/faculty/faculty-profile' },
    facultyReport: { title: 'Faculty Report', link: '/faculty/service/generateFacultyReport' },
    facultyLogin: { title: 'Faculty Login', link: '/faculty-login' },
    facultyPasswordReset: { title: "Faculty Password Reset", link: '/services/forgot-password/faculty' },
    facultyRegistration: { title: 'Faculty Registration', link: '/faculty-registration' },
    contractualFacultyRegistration: { title: 'Contractual Faculty Registration', link: '/contractual-faculty-registration' },
    facultyChangePass: { title: 'Change Password', link: '/changePassword' },
    cas: { title: 'CAS Report', link: '/faculty/service/cas-report' },
    casReport: { title: 'Generate CAS Report', link: '/faculty/service/generateCASReport' },
    pbas: { title: 'PBAS Report', link: '/faculty/service/pbas-report' },
    pbasReport: { title: 'Generate PBAS Report', link: '/faculty/service/generatePBASReport' },
    aaaReport: { title: 'Academic & Administrative Audit Report', link: '/director/service/generateAAAReport' },
    directorReport: { title: 'Director Report', link: '/director/service/generateDirectorReport' },
    directorPasswordReset: { title: "Director Password Reset", link: '/services/forgot-password/director' },
    directorHome: { title: 'Director Home', link: '/director' },
    directorLogin: { title: 'Director Login', link: '/director-login' },
    directorRegistration: { title: 'Director Registration', link: '/director-registration' },
    sdm: { title: 'SDM', link: '/director/sdm' },
    aaa: { title: 'Academic Audit  ', link: '/director/service/academic-audit' },
    alumniLogin: { title: 'Alumni Login', link: '/alumni-login' },
    alumniHome: { title: 'Alumni Home', link: '/alumni' },
    alumniPasswordReset: { title: "Alumni Password Reset", link: '/services/forgot-password/alumni' },
    alumniRegistration: { title: 'Alumni Registration', link: '/alumni-registration' },
    alumniStatus: { title: 'Alumni Status', link: '/alumni/alumni-status' },
    studentLogin: { title: "Student Login", link: '/student-login' },
    studentHome: { title: "Student Home", link: '/student' },
    studentRegistration: { title: "Student Registration", link: '/student-registration' },
    studentPasswordReset: { title: "Student Password Reset", link: '/services/forgot-password/student' },
    studentStatus: { title: "Student Status", link: '/student/student-status' },
    allNews: { title: "All News", link: '/news' },
    proLogin: { title: "PRO Login", link: '/pro-login' },
    proEditor: { title: "PRO Editor", link: '/pro-editor' },
    proHome: { title: "PRO Home", link: '/pro' },



    forgotPassword: { title: "Forgot Password", link: '' }
}
export default siteLinks;
