const TableData = {
  nameOfTheProgramsOffered: [
    "Year",
    "UG",
    "PG",
    "M.Phil",
    "Ph.D.",
    "Diploma/Certificate Course",
  ],
  numberOfTeachingPostsSanctionedFilledAndVacant: [
    "Designation",
    "Sanctioned",
    "Filled",
    "Filled Under CAS",
  ],
  appointedOnGovernmentSanctionedPost: [
    "Name",
    "Designation",
    "Qualifications",
    "Teaching/Research Experience",
    "Nature Of Appointment",
  ],
  appointedFromUniversityFund: [
    "Name",
    "Designation",
    "Qualifications",
    "Teaching/Research Experience",
    "Nature Of Appointment",
  ],
  listOfVisitingFellowsTeachersAdjunctAndEmeritusProfessors: [
    "Name Of The Teacher",
    "Designation",
    "Gender",
    "Qualification",
    "Institute Address",
  ],
  numberOfAcademicSupportStaffAndAdministrativeStaffSanctionedFilledAndVacant: [
    "Sr. No.",
    "Name Of The Post",
    "Sanctioned Posts",
    "Filled",
    "Vacant",
  ],
  fromNationalInternationalFundingAgencies: [
    "Sr. No.",
    "Name Of The Principle Investigator (C0-Investigator)",
    "Title Of The Project",
    "Funding Agency, Duration & Date Of Sanction",
    "Amount (in Lakh)",
    "Remarks if any",
  ],
  fromNGOIndustriesAnyOtherNonGovtAgencies: [
    "Sr. No.",
    "Name Of The Principle Investigator (C0-Investigator)",
    "Title Of The Project",
    "Funding Agency, Duration & Date Of Sanction",
    "Amount (in Lakh)",
    "Remarks if any",
  ],
  fundsReceivedAtSchoolLevel: [
    "Scheme And Funding Agency",
    "Non- Recurring",
    "Recurring",
    "Project Fellow",
    "Total",
  ],
  publicationDetails: [
    "Sr. No.",
    "Papers Published In Peer Reviewed Journals",
    "Monographs, Books, Chapters In Books",
    "Citations",
    "h-Index",
    "Impact Factor Range / Average Impact Factor",
  ],
  detailsOfPatentsFiledAndGrantedAndIncomeGenerated: [
    "Sr. No.",
    "Number Of Patents Filed",
    "Number Of Patents Published",
    "Number Of Patents Granted",
  ],
  consultancyServicesProvidedNameOfTheTeachersAndIncomeGenerated: [
    "Sr. No.",
    "Year",
    "Name Of The Teacher",
    "Nature Of Consultancy",
    "Funds Generated (In Lakh)",
  ],
  participationOfTeachersInVariousAcademicActivitiesAsMembersOfCommittees: [
    "Name of the teacher",
    "Name of the committee",
    "Position In The Committee( Director, Coordinator, Member, etc)",
    "Level",
  ],
  detailsOfSeminarsConferencesWorkshopsOrganized: [
    "Name Of Conference / Seminars / Workshops",
    "Funding Agency",
    "No Of Participants",
    "University / State / National / International",
    "Dates",
  ],
  detailOfSyllabusRevision: [
    "Year Of Revision",
    "Program",
    "Courses Revised",
    "Courses Added (With Reason)",
    "Courses Removed (With Reason)",
    "Define The Type Of Revision-Content / Assessment Pattern / Any Other Change",
    "% Of Revision",
  ],
  howManyCoursesInTheSyllabusAreIdentifiedAsSkillEntrepreneurshipBasedCoursesHavingAttachedActivitiesDuringTheSemester:
    [
      "Name Of The Ccourse (With No Of Credits)",
      "Program",
      "Details Of Employability / Skill Development / Entrepreneurship Related Activity Carried Out To Support This Course. Give Details Of MoUs With Relevant Organizations For These Courses,(If Any",
    ],
  valueAadditionCoursesForImpartingTransferableAndLifeSkillsOffered: [
    "Name Of The Course",
    "No Of Hours (Minimum 30 Hours)",
    "Run In Year...",
    "No Of Time Per Year",
    "Noof Students Enrolled",
  ],
  hasTheSchoolIncorporatedTopicsCoursesRelevantToProfessionalEthicsGenderHumanValuesEnvironmentAndSustainabilityIntoTheCurriculum:
    [
      "Name Of The Program ",
      "Course Code ",
      "Name Of The Course ",
      "Description Of The Course",
    ],
  programObjectiveAndOutcomes: [
    "Program Name",
    "Program Educational Objectives (PEO)",
    "PROGRAMME OUTCOMES (PO)",
    "PROGRAMME SPECIFIC OUTCOMES (PSO)",
  ],
  courceObjectiveAndOutcomes: [
    "Program Name",
    "Course Code",
    "Course Name",
    "Course Objectives",
    "Course Outcomes (CO)",
  ],
  studentProfileProgrammewiseAtUGAndPG: [
    "UG / PG / Diploma / Certificate",
    "Applications Received",
    "No. Of Students Admitted",
    "Seats Available",
    "Male",
    "Female",
    "Total",
    "Year",
  ],
  yearWiseResultsOfStudentsAtUGAndPG: [
    "Program name",
    "Type : UG / PG / Diploma / PG Diploma/Certificate",
    "Year",
    "Appeared",
    "Passed",
    "Pass %",
  ],
  informationAboutJRFSRFOtherFellowships: [
    "Sr. No.",
    "Name Of Research Fellow",
    "Year Of Enrolment",
    "Duration Of Fellowship",
    "Type of  the fellowship",
    "Granting agency",
    "Qualifying Exam If Any (NET, GATE)",
  ],
  informationAboutMPhilProgramme: [
    "Year",
    "Applications Received",
    "Intake",
    "No. Of Students Admitted",
    "Male ",
    "Female ",
    "Total",
  ],
  informationAboutPhDProgramme: [
    "Year",
    "Applications Received",
    "Intake",
    "No. Of Students Admitted",
    "Male ",
    "Female ",
    "Total",
  ],
  tudentDemandRatioProgramWise: [
    "Name Of The Program",
    "Demand Ratio"
  ],
  studentTeacherRatioProgramWise: [
    "Name Of The Program",
    "Student-Teacher Ratio",
  ],
  numberOfStudentsAwardedMPhilPhDDegree: [
    "Year",
    "M.Phil",
    "Ph.D.",
    "Total"
  ],
  numberOfStudentsClearedCivilServicesAndDefenseServicesExaminationsNETSETGATEAndOtherCompetitiveExaminations: [
      "Year",
      "MPSC / UPSC",
      "NET / SET",
      "GATE",
      "Other Exams",
      "Total"
  ],
  studentProgressionPlacementRecordNumberPercentageOfStudentsProceededForHigherStudiesNumberPercentageOfStudentsPlaced: [
      "Year",
    "No Of Students For Higher Studies",
    "No Of Students Placed"
  ],
};

